import 'package:transmission_rpc/transmission_rpc.dart';

extension SessionSet on Transmission {
  Future<void> setSession({
    int? altSpeedDown,
    bool? altSpeedEnabled,
    int? altSpeedTimeBegin,
    int? altSpeedTimeDay,
    bool? altSpeedTimeEnabled,
    int? altSpeedTimeEnd,
    int? altSpeedUp,
    bool? blocklistEnabled,
    String? blocklistUrl,

    /// MB
    String? cacheSize,
    String? defaultTrackers,
    bool? dhtEnabled,
    String? downloadDir,
    bool? downloadQueueEnabled,
    int? downloadQueueSize,
    String? encryption,
    bool? idleSeedingLimitEnabled,
    int? idleSeedingLimit,
    bool? incompleteDirEnabled,
    String? incompleteDir,
    bool? lpdEnabled,
    int? peerLimitGlobal,
    int? peerLimitPerTorrent,
    bool? peerPortRandomOnStart,
    int? peerPort,
    bool? pexEnabled,
    bool? portForwardingEnabled,
    bool? queueStalledEnabled,
    int? queueStalledMinutes,
    bool? renamePartialFiles,
    bool? scriptTorrentAddedEnabled,
    String? scriptTorrentAddedFilename,
    bool? scriptTorrentDoneEnabled,
    String? scriptTorrentDoneFilename,
    bool? scriptTorrentDoneSeedingEnabled,
    String? scriptTorrentDoneSeedingFilename,
    bool? seedQueueEnabled,
    int? seedQueueSize,
    double? seedRatioLimit,
    bool? seedRatioLimited,
    bool? speedLimitDownEnabled,
    int? speedLimitDown,
    bool? speedLimitUpEnabled,
    int? speedLimitUp,
    bool? startAddedTorrents,
    bool? trashOriginalTorrentFiles,
    bool? utpEnabled,
  }) async {
    await sendRawRequest(
      TransmissionRequest(method: "session-set", arguments: {
        if (altSpeedDown != null) "alt-speed-down": altSpeedDown,
        if (altSpeedEnabled != null) "alt-speed-enabled": altSpeedEnabled,
        if (altSpeedTimeBegin != null) "alt-speed-time-begin": altSpeedTimeBegin,
        if (altSpeedTimeDay != null) "alt-speed-time-day": altSpeedTimeDay,
        if (altSpeedTimeEnabled != null) "alt-speed-time-enabled": altSpeedTimeEnabled,
        if (altSpeedTimeEnd != null) "alt-speed-time-end": altSpeedTimeEnd,
        if (altSpeedUp != null) "alt-speed-up": altSpeedUp,
        if (blocklistEnabled != null) "blocklist-enabled": blocklistEnabled,
        if (blocklistUrl != null) "blocklist-url": blocklistUrl,
        if (cacheSize != null) "cache-size-mb": cacheSize,
        if (defaultTrackers != null) "default-trackers": defaultTrackers,
        if (dhtEnabled != null) "dht-enabled": dhtEnabled,
        if (downloadDir != null) "download-dir": downloadDir,
        if (downloadQueueEnabled != null) "download-queue-enabled": downloadQueueEnabled,
        if (downloadQueueSize != null) "download-queue-size": downloadQueueSize,
        if (encryption != null) "encryption": encryption,
        if (idleSeedingLimitEnabled != null) "idle-seeding-limit-enabled": idleSeedingLimitEnabled,
        if (idleSeedingLimit != null) "idle-seeding-limit": idleSeedingLimit,
        if (incompleteDirEnabled != null) "incomplete-dir-enabled": incompleteDirEnabled,
        if (incompleteDir != null) "incomplete-dir": incompleteDir,
        if (lpdEnabled != null) "lpd-enabled": lpdEnabled,
        if (peerLimitGlobal != null) "peer-limit-global": peerLimitGlobal,
        if (peerLimitPerTorrent != null) "peer-limit-per-torrent": peerLimitPerTorrent,
        if (peerPortRandomOnStart != null) "peer-port-random-on-start": peerPortRandomOnStart,
        if (peerPort != null) "peer-port": peerPort,
        if (pexEnabled != null) "pex-enabled": pexEnabled,
        if (portForwardingEnabled != null) "port-forwarding-enabled": portForwardingEnabled,
        if (queueStalledEnabled != null) "queue-stalled-enabled": queueStalledEnabled,
        if (queueStalledMinutes != null) "queue-stalled-minutes": queueStalledMinutes,
        if (renamePartialFiles != null) "rename-partial-files": renamePartialFiles,
        if (scriptTorrentAddedEnabled != null) "script-torrent-added-enabled": scriptTorrentAddedEnabled,
        if (scriptTorrentAddedFilename != null) "script-torrent-added-filename": scriptTorrentAddedFilename,
        if (scriptTorrentDoneEnabled != null) "script-torrent-done-enabled": scriptTorrentDoneEnabled,
        if (scriptTorrentDoneFilename != null) "script-torrent-done-filename": scriptTorrentDoneFilename,
        if (scriptTorrentDoneSeedingEnabled != null)
          "script-torrent-done-seeding-enabled": scriptTorrentDoneSeedingEnabled,
        if (scriptTorrentDoneSeedingFilename != null)
          "script-torrent-done-seeding-filename": scriptTorrentDoneSeedingFilename,
        if (seedQueueEnabled != null) "seed-queue-enabled": seedQueueEnabled,
        if (seedQueueSize != null) "seed-queue-size": seedQueueSize,
        if (seedRatioLimit != null) "seedRatioLimit": seedRatioLimit,
        if (seedRatioLimited != null) "seedRatioLimited": seedRatioLimited,
        if (speedLimitDownEnabled != null) "speed-limit-down-enabled": speedLimitDownEnabled,
        if (speedLimitDown != null) "speed-limit-down": speedLimitDown,
        if (speedLimitUpEnabled != null) "speed-limit-up-enabled": speedLimitUpEnabled,
        if (speedLimitUp != null) "speed-limit-up": speedLimitUp,
        if (startAddedTorrents != null) "start-added-torrents": startAddedTorrents,
        if (trashOriginalTorrentFiles != null) "trash-original-torrent-files": trashOriginalTorrentFiles,
        if (utpEnabled != null) "utp-enabled": utpEnabled,
      }),
    );
  }
}
